export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const GET_USER_BY_EMAIL = 'GET_USER_BY_EMAIL';
export const LOGGOUT_USER = 'LOGGOUT_USER';
export const REGISTER_MSG = 'REGISTER_MSG';
export const SEND_SERVER_MSG = 'SEND_SERVER_MSG';